ignore:
  - "webapp/e2e/**"
  - "webapp/public/**"
  - "webapp/loadtestexample/**"
  - "webapp/src/test/**"
  - "webapp/src/api/**"
  - "webapp/src/*.[tsx, ts, css]"
  - "webapp/src/styles/**"
  - "webapp/src/shared/**"
  - "webapp/src/img/**"
  - "docs/**"
  - "data/**"
  - "webapp/src/components/DisplayRelatedProducts.tsx"
  - "webapp/src/components/DistributionCenterDisplay.tsx"
  - "webapp/src/components/GoToTopButton.tsx"
  - "webapp/src/components/HandleAddToCart.tsx"
  - "webapp/src/components/HandleRemoveFromCart.tsx"
  - "webapp/src/components/LoggedView.tsx"
  - "webapp/src/components/LoginSolid.tsx"
  - "webapp/src/components/ProductDetailModal.tsx"
  - "webapp/src/components/HorizontalSeparator.tsx"
  - "webapp/src/components/ItemDetails.tsx"
  - "webapp/src/components/RelatedProduct.tsx"