version: '3.5'
services:
  restapi:
    image: ghcr.io/arquisoft/dede_es3c/restapi:latest
    ports:
      - "5000:5000"
  webapp:
    image: ghcr.io/arquisoft/dede_es3c/webapp:latest
    ports:
      - "3000:3000"
    depends_on: 
      - restapi
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: SergioArroni
      MONGO_INITDB_ROOT_PASSWORD: julio321
      MONGO_INITDB_DATABASE: DeDesktop
    ports:
      - "27017:27017"
  python:
    image: ghcr.io/arquisoft/dede_es3c/python:latest
    ports:
      - "8000:8000"
    depends_on: 
      - mongo