version: '3.5'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  restapi:
    build: ./restapi
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    depends_on:
      - restapi
  prometheus:
    image: prom/prometheus
    volumes:
      - ./restapi/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - restapi
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./restapi/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - restapi
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: SergioArroni
      MONGO_INITDB_ROOT_PASSWORD: julio321
      MONGO_INITDB_DATABASE: DeDesktop
    ports:
      - "27017:27017"
  python:
    build: ./data
    image: python
    ports:
      - "8000:8000"
    depends_on: 
      - mongo

